### ISSUE TITLE
Confusion by the Type Declarations on `persistentMap`

### ISSUE THREAD

**Issue by Bwvolleyball** [nanostores/persistent#37]
I am trying to implement a `persistentMap` with a complex object type, but I'm very confused by the type declarations between the `PersistentEncoder` and the `opts` for `persistentMap`.

It feels like these don't line up?

the options claims to require this: https://github.com/nanostores/persistent/blob/main/index.d.ts#L84

specifically, this `PersistentEncoder<Value[keyof Value]>`, where value is the generic object.  My bigger question is why / how is it this `Value[keyof Value]`?? Shouldn't it just be `Value`, as in `PersistentEncoder<Value>`.

I do not know how to take a complex object type `T`, and create an object instance that satisfies `T[keyof T]` any and all guidance would be very much appreciated.

Here's my example code:

```typescript
const emptyValue = verifyAndCreate(MyComplexObject)({});

const opts: PersistentSimpleOptions & PersistentEncoder<MyComplexObject> = {
    listen: true,
    encode (value) {
        return JSON.stringify(value)
    },
    decode(encoded): MyComplexObject {
        const raw = JSON.parse(encoded)
        return verifyAndCreate(MyComplexObject)(raw)
    }
}
export const mappedMyObjects = persistentMap<MyComplexObject>("my_object:", emptyValue, opts);
```

if it matters, `MyComplexObject` is a generated protobuf message, and `verifyAndCreate` is a helper that ensures we are returning an object of the correct type, essentially, and it makes typescript happy.

Essentially, it's telling me that it cannot create `mappedMyObjects` because `opts` is of the wrong type. How do these types even line up?

**Comment by ai** [comment]
>  Shouldn't it just be Value, as in PersistentEncoder<Value>.

No, according to API, we call encoder for every key of map.
* Code: https://github.com/nanostores/persistent/blob/main/index.js#L100
* Test: https://github.com/nanostores/persistent/blob/main/test/map.test.ts#L131-L154

> I do not know how to take a complex object type T

This API was not created for your case. The store keep every map’s key in separated `localStorage` record. So you need to encode/decode them separately.

Why you don’t want to use `persistentAtom`? If you have a single structure in `MyComplexObject` (for instance, big object with one option of settings), it should be stored in a single record.

Also, I think we can add `key` argument to `encode()`/`decode()` functions. It could simplify `verifyAndCreate()` (because you will know what key you encode), but you still need to think about map as a list of objects (like list of settings) to use `persistentMap`.

**Comment by Bwvolleyball** [comment]
Hmm, gotcha - I might be attempting the wrong thing then with this `persistentMap` - I have many `MyComplexObjects`, each with a specific id, in my head a `persistentMap` would allow me to store each of these objects by their specific id, but it seems that this is the wrong way to think of `persistentMap`?

In my head, I could have created a map like this:

```
{
    "uuid1": {/* MyComplexObject 1 */},
    "uuid2": {/* MyComplexObject 1 */},
/// ...
}
```

But it seems that is not the case?

**Comment by ai** [comment]
In this case, `persistentMap` will work fine (every object will be in separated record). But here you don’t need `key` in `decode()` because every key have the same type.

Try this:

```ts
interface MyComplexObject {
  …
}

type MyComplexObjectStorage = Record<string, MyComplexObject>

export const mappedMyObjects = persistentMap<MyComplexObjectStorage>(
  'my_object:',
  {},
  {
    listen: true,
    encode(value) {
      return JSON.stringify(value)
    },
    decode(encoded) {
      let raw = JSON.parse(encoded)
      return { id: raw.id!, name: raw.name! }
    }
  }
)
```

`encode()` and `decode()` will automatically get types from store and have right types of accepting/returning `MyComplexObject`.

**Comment by Bwvolleyball** [comment]
Ah, thank you! That is super helpful to see, I appreciate the example!
