### ISSUE TITLE
Possibility to support a TTL for persistentAtom to auto clear it after a set amount of time?

### ISSUE THREAD

**Issue by Bwvolleyball** [nanostores/persistent#50]
Like the title says, can `persistantAtom()` support a TTL to auto clear it's value after an amount of time has passed and consider the persistent atom invalid?

**Comment by ai** [comment]
You can add it with `onMount`.

Then you can publish it to npm like other smart stores. For instance like https://github.com/nanostores/persistent

**Comment by ai** [comment]
We are not going to add it to the `persistantAtom` because it will bloat JS bundle even for people who don't need this feature.

But it is very easy to add it on top of `persistantAtom`. Just create function like `createTTLAtom` where you will create `persistantAtom` and use `onMount` to add timeout (you can even publish it to npm and we will add your project to smart stores list).

**Comment by Bwvolleyball** [comment]
Makes sense @ai - do you happen to have a link to a small working example to demonstrate this?

**Comment by ai** [comment]
I can write a pseudo-code:

```js
import { onMount } from 'nanostores'

function ttlPersistant(initial, timeout) {
  let atom = persistantAtom(initial)
  onMount(atom, () => { // replace to onSet if you need to clear after setting the value
    setTimeout(() => {
      atom.set(initial)
    }, timeout)
  })
  return atom
}
```

**Comment by ai** [comment]
The full list of atom’s events https://github.com/nanostores/nanostores#store-events
